-- Add additional fields to employees table for offer letter generation
ALTER TABLE employees
ADD COLUMN address TEXT AFTER designation,
ADD COLUMN permanent_address TEXT AFTER address,
ADD COLUMN dob DATE AFTER permanent_address,
ADD COLUMN gender ENUM('male', 'female', 'other') AFTER dob,
ADD COLUMN marital_status ENUM('single', 'married', 'divorced', 'widowed') AFTER gender,
ADD COLUMN emergency_contact_name VARCHAR(255) AFTER marital_status,
ADD COLUMN emergency_contact_phone VARCHAR(20) AFTER emergency_contact_name,
ADD COLUMN joining_date DATE AFTER emergency_contact_phone,
ADD COLUMN employment_type ENUM('full_time', 'part_time', 'contract', 'intern') DEFAULT 'full_time' AFTER joining_date,
ADD COLUMN probation_period VARCHAR(10) DEFAULT '3' AFTER employment_type,
ADD COLUMN basic_salary DECIMAL(10, 2) AFTER probation_period,
ADD COLUMN hra DECIMAL(10, 2) AFTER basic_salary,
ADD COLUMN conveyance DECIMAL(10, 2) AFTER hra,
ADD COLUMN medical_allowance DECIMAL(10, 2) AFTER conveyance,
ADD COLUMN lta DECIMAL(10, 2) AFTER medical_allowance,
ADD COLUMN other_allowances DECIMAL(10, 2) AFTER lta,
ADD COLUMN previous_company VARCHAR(255) AFTER other_allowances,
ADD COLUMN previous_designation VARCHAR(255) AFTER previous_company,
ADD COLUMN experience_years INT AFTER previous_designation,
ADD COLUMN qualification VARCHAR(255) AFTER experience_years,
ADD COLUMN bank_account VARCHAR(50) AFTER qualification,
ADD COLUMN pan_number VARCHAR(20) AFTER bank_account;
