-- Password reset with Email OTP: allowed columns only
ALTER TABLE employees ADD COLUMN IF NOT EXISTS otp VARCHAR(255) NULL;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS otpExpiry DATETIME NULL;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS otpAttempts INT NOT NULL DEFAULT 0;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS resetVerified TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS resendCooldown DATETIME NULL;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS tokenVersion INT NOT NULL DEFAULT 0;
